CREATE TABLE bookings (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_reference VARCHAR(36)              NOT NULL UNIQUE,
    event_id          BIGINT                   NOT NULL,
    event_name        VARCHAR(255)             NOT NULL,
    customer_name     VARCHAR(255)             NOT NULL,
    customer_email    VARCHAR(255)             NOT NULL,
    quantity          INTEGER                  NOT NULL,
    unit_price        NUMERIC(12, 2)           NOT NULL,
    total_amount      NUMERIC(14, 2)           NOT NULL,
    status            VARCHAR(20)              NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_bookings_event_id ON bookings (event_id);
CREATE INDEX idx_bookings_customer_email ON bookings (customer_email);
