CREATE TABLE events (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(255)             NOT NULL,
    description       VARCHAR(2000),
    venue             VARCHAR(255)             NOT NULL,
    city              VARCHAR(255)             NOT NULL,
    event_date_time   TIMESTAMP WITH TIME ZONE NOT NULL,
    total_tickets     INTEGER                  NOT NULL,
    available_tickets INTEGER                  NOT NULL,
    ticket_price      NUMERIC(12, 2)           NOT NULL,
    status            VARCHAR(20)              NOT NULL DEFAULT 'SCHEDULED',
    version           BIGINT                   NOT NULL DEFAULT 0,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT chk_available_non_negative CHECK (available_tickets >= 0),
    CONSTRAINT chk_available_le_total     CHECK (available_tickets <= total_tickets)
);

CREATE INDEX idx_events_status ON events (status);
CREATE INDEX idx_events_event_date_time ON events (event_date_time);
