CREATE TABLE ticket_sales (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     BIGINT                   NOT NULL REFERENCES events (id),
    quantity     INTEGER                  NOT NULL,
    unit_price   NUMERIC(12, 2)           NOT NULL,
    total_amount NUMERIC(14, 2)           NOT NULL,
    sold_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- The batch job aggregates by day, so index the sale timestamp.
CREATE INDEX idx_ticket_sales_sold_at ON ticket_sales (sold_at);
CREATE INDEX idx_ticket_sales_event_id ON ticket_sales (event_id);
