-- Per-event daily sales rollup, produced by the Spring Batch job.
-- One row per (report_date, event_id); the job is idempotent (a re-run for a
-- date first deletes that date's rows, then re-inserts).
CREATE TABLE daily_event_sales_report (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_date   DATE                     NOT NULL,
    event_id      BIGINT                   NOT NULL,
    event_name    VARCHAR(255)             NOT NULL,
    tickets_sold  BIGINT                   NOT NULL,
    revenue       NUMERIC(16, 2)           NOT NULL,
    generated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_daily_report_date_event UNIQUE (report_date, event_id)
);

CREATE INDEX idx_daily_report_date ON daily_event_sales_report (report_date);
