CREATE TABLE notifications (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_reference VARCHAR(36)              NOT NULL UNIQUE,
    recipient_email   VARCHAR(255)             NOT NULL,
    channel           VARCHAR(20)              NOT NULL,
    status            VARCHAR(20)              NOT NULL,
    message           VARCHAR(1000)            NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_notifications_recipient ON notifications (recipient_email);
